#!/bin/bash

#SBATCH --job-name=installMiniconda     # Job name
#SBATCH --output=job.%j.out             # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8               # Schedule one core
#SBATCH --time=00:30:00                 # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=red,brown           # Run on either the Red or Brown queue

# Print out the hostname of the node the job is running on
#hostname
# Download from https://docs.conda.io/en/latest/miniconda.html#linux-installers
bash ./Miniconda3-py39_23.1.0-1-Linux-x86_64.sh -b -p ~/miniconda3
~/miniconda3/bin/conda init
