#!/bin/bash

#SBATCH --job-name=setupEnvironment    # Job name
#SBATCH --output=job.%j.out            # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=1              # Schedule one core
#SBATCH --time=00:20:00                # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=red,brown          # Run on either the Red or Brown queue

# Print out the hostname of the node the job is running on
hostname
conda env create --file=environment.yml
